### ISSUE TITLE
无法登陆web界面

### ISSUE THREAD

**Issue by ID404** [leniy/docker-cacti#3]
登陆web界面时有如下提示：
FATAL: Cannot connect to MySQL server on 'localhost'. Please make sure you have specified a valid MySQL database name in 'include/config.php'

**Comment by leniy** [comment]
您是直接使用我在docker官方仓库中发布的编译好的包，还是用这个源码自己编译的？

**Comment by peach0706** [comment]
登陆web界面时有如下提示：
FATAL: Cannot connect to MySQL server on 'localhost'. Please make sure you have specified a valid MySQL database name in 'include/config.php'

直接在docker 仓库pull下来的images

**Comment by leniy** [comment]
@peach0706 
是的。最近docker接口变动的比较多，我上次更新代码，docker hub自动重新编译过了。
我检查一下

**Comment by leniy** [comment]
@ID404 @peach0706 
问题解决了，新版本的服务器没有用mysql而是mysqli，测试已经通过，我正在重新部署到docker仓库中
